version: '3.4'

services:
  voting-app:
    image: voting-app:${APP_TAG}
    environment:
      - API_BASE_URL=${API_BASE_URL}:${API_PORT}
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - voting-api
    build:
      context: ./src/VotingApp/
      dockerfile: ${PWD:-.}/VotingApp.Dockerfile
  voting-api:
    image: voting-api:${APP_TAG}
    ports:
      - "${API_PORT}:80"
    build:
      context: ./src/VotingApi/VotingApi.Api/
      dockerfile: ${PWD:-.}/VotingApi.Dockerfile

