version: '3.4'

services:
  voting-app:
    image: voting-app:v1
    environment:
      - API_BASE_URL=http://localhost:8081
    ports:
      - "8080:80"
    depends_on:
      - voting-api
    build:
      context: ./src/VotingApp/
      dockerfile: ${PWD:-.}/VotingApp.Dockerfile
  voting-api:
    image: voting-api:v1
    ports:
      - "8081:80"
    build:
      context: ./src/VotingApi/VotingApi.Api/
      dockerfile: ${PWD:-.}/VotingApi.Dockerfile

