name: DeployFrontApp

on:
  push:
    branches: [ main ]
    paths:
    - 'src/VotingApp/**'
    - 'VotingApp.Dockerfile'
    
  pull_request:
    branches: [ main ]

env:
  version: $(date +%s)
  AKS_NAME: ${{ secrets.AKS_NAME }}
  AKS_RG_NAME: ${{ secrets.AKS_RG_NAME }}
  ACR_URL: 'powoeuwacr.azurecr.io'
  OUTPUT_DIR: 'out'
  DOMAIN: ${{ secrets.DOMAIN }}
  NAMESPACE: 'voting'
  APP_NAME: 'voting-app'
  DEPLOYMENT_FILE_NAME: 'voting-app.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set IMAGE_ID env variable
      run: |
        echo "IMAGE_ID=${{ env.ACR_URL }}/${{ env.APP_NAME }}:v${{ github.run_number }}" >> $GITHUB_ENV
    - name: Print IMAGE_ID
      run: |
        echo "IMAGE_ID:${{ env.IMAGE_ID }}"
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ env.ACR_URL }}
        username: ${{ secrets.ACR_USER_ID }}
        password: ${{ secrets.ACR_USER_PASSWORD }}
    - name: Build docker image
      run: |
        docker build -f VotingApp.Dockerfile src/VotingApp/. -t ${{ env.IMAGE_ID }}
    - name: Push docker image
      run: |
        docker push ${{ env.IMAGE_ID }}